# Generated by Django 6.0.1 on 2026-03-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('In processing', 'In processing'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=50, null=True),
        ),
    ]
