# Generated by Django 6.0.1 on 2026-03-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Staff', 'Staff')], max_length=20, null=True),
        ),
    ]
