# Generated by Django 6.0.1 on 2026-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
