# Generated by Django 6.0.1 on 2026-03-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_users_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_project',
            field=models.CharField(blank=True, choices=[('In processing', 'In processing'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], max_length=50, null=True),
        ),
    ]
