# Generated by Django 6.0.3 on 2026-03-15 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_comment_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTask',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_task', to='main.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
