# Generated by Django 6.0.3 on 2026-03-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_commenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttask',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_task', to='main.project'),
            preserve_default=False,
        ),
    ]
