# Generated by Django 6.0.3 on 2026-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
